POST http://127.0.0.1:5000/getusers HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjF3Y0FhM1lGNFVHVGVuWWd5OUhuRCJ9.eyJpc3MiOiJodHRwczovL3dlYmluZm9wcm9qZWN0LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NzUwNzQwMDQyYTE1MTI5M2JlMzdmYmEiLCJhdWQiOlsiaHR0cHM6Ly9hdXRoMC1ncmFwaHFsLWFwaSIsImh0dHBzOi8vd2ViaW5mb3Byb2plY3QuZXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTczMzQwNTMzNSwiZXhwIjoxNzMzNDkxNzM1LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiZ3R5IjoicGFzc3dvcmQiLCJhenAiOiJwNDRaUG90MDRoY2NubmtQR3R4N0VMV0VadnltMHlEaSJ9.cA8gq7pAYX_kWHJb_tUmZq_VyxZyOM4kMruMZTwtNjIk5Jejp3ikQhMR2GTgRoOsGA48v4k5O2nIPcSdF2c5Ya6epzj_Gppif25NWoYW1xHGH270goQov8P4urEIkjpjGtbTJkM6UhL_sF214UwPz17GWfMSXSO0BC-1k2AwTA_uBY81v9_wEH35JYu_d0_BOK22iqqYMSR-yOe72kuIw5HkmI6-4cgox8NB-CKXIhVL_Xi9Rcgj-kYONwgOc9QiLufe_MN3XZS9ITVYSsyPjCddkMfuRMMvlXhvR-oK50DOr3F3G4zT0mA_0L4Ad9iWSkDmpKbqpJON35H2ondwbQ
Content-Type: application/json

{
  "query": "query { users { id firstName name email location { country city cityCode street houseNumber } } }"
}