POST http://127.0.0.1:5000/getusers HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjF3Y0FhM1lGNFVHVGVuWWd5OUhuRCJ9.eyJpc3MiOiJodHRwczovL3dlYmluZm9wcm9qZWN0LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJwNDRaUG90MDRoY2NubmtQR3R4N0VMV0VadnltMHlEaUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC1ncmFwaHFsLWFwaSIsImlhdCI6MTczMzM0ODAyNSwiZXhwIjoxNzMzNDM0NDI1LCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJwNDRaUG90MDRoY2NubmtQR3R4N0VMV0VadnltMHlEaSJ9.DhpQNvoMkeBhNMF11ObuPmdrP_wZFFrnC90WsYc6KzR4U3HMkSrlmOawnHJal4hq4Z7h-qLpixCTi9mIx1EsvDVeKPClU1CMkO7-wW-Qqr3rOV0CsfBTYX6vXhf4HBjlAHydTjWRocX8sVwp3HZcWoQYBOYcUBO0n2ihuRshq5GEl3YofHrNPCuubdKT03XAlQgF02vvJaM3qi0dP6C6ZwkDNLnSA8FetP9I74_dat47R31_a1T3Kawh4qWMWYt9iJEJX0cUiHj1SR30bz0I4r-flYFP8hF7aKsavquz-uO0lqTyq6_TKfAAkE9i48OkpvqJmt15lwR12jd-wO-oJA
Content-Type: application/json

{
  "query": "query { users { id firstName name email location { country city cityCode street houseNumber } } }"
}